image: docker:19.03

services:
  - name: docker:19.03-dind
    command: ["--experimental"]

variables:
  APP_VERSION: $CI_COMMIT_REF_NAME
  REGISTRY: $CI_REGISTRY_IMAGE
  BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64

before_script:
  - mkdir -p ~/.docker/cli-plugins
  - wget $BUILDX_URL -O ~/.docker/cli-plugins/docker-buildx
  - chmod +x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use --name new_builder
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build

pgrok:
  stage: build
  script:
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --push -t $REGISTRY:$APP_VERSION -t $REGISTRY .
