env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io
before:
  hooks:
    - make deps
    - make assets
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    main: ./cmd/pgrok/main.go
    id: pgrok
    binary: pgrok
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    main: ./cmd/pgrokd/main.go
    id: pgrokd
    binary: pgrokd
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
archives:
  - id: pgrokd
    builds:
      - pgrokd
    name_template: "pgrokd_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
  - id: pgrok
    builds:
      - pgrok
    name_template: "pgrok_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: pgrok
    ids:
      - pgrok
    github:
      owner: jerson
      name: homebrew-tap
    commit_author:
      name: Gerson Alexander Pardo Gamez
      email: jeral17@gmail.com
    folder: Formula
    homepage: "https://github.com/jerson/pgrok"
    description: "Introspected tunnels to localhost a fork from pgrok."
    install: |
      bin.install "pgrok"
    test: |
      system "#{bin}/pgrok", "-v"
  - name: pgrokd
    ids:
      - pgrokd
    github:
      owner: jerson
      name: homebrew-tap
    commit_author:
      name: Gerson Alexander Pardo Gamez
      email: jeral17@gmail.com
    folder: Formula
    homepage: "https://github.com/jerson/pgrok"
    description: "Server introspected tunnels to localhost a fork from pgrok."
    install: |
      bin.install "pgrokd"
    test: |
      system "#{bin}/pgrokd", "-v"
scoop:
  - id: pgrok
    bucket:
      owner: jerson
      name: scoop-bucket
    commit_author:
      name: Gerson Alexander Pardo Gamez
      email: jeral17@gmail.com
    homepage: "https://github.com/jerson/pgrok"
    description: "Introspected tunnels to localhost a fork from pgrok."
    license: MIT
  - id: pgrokd
    bucket:
      owner: jerson
      name: scoop-bucket
    commit_author:
      name: Gerson Alexander Pardo Gamez
      email: jeral17@gmail.com
    homepage: "https://github.com/jerson/pgrok"
    description: "Server introspected tunnels to localhost a fork from pgrok."
    license: MIT
